# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: pip install ansible==v2.9.0rc5
  displayName: 'install ansible'

- script: |
    ansible-galaxy collection build
  displayName: 'build collection'
