authors:
  - "azure"
dependencies:
description:
documentation:
homepage:
issues:
license:
  - "MIT"
name: azuretest
namespace: gavinfish
readme: README.md
repository: 'https://github.com/gavinfish/azuretest'
tags:
  - "test"
version: 1.0.3
